### ISSUE TITLE
issue with linking to Test Plan

### ISSUE THREAD

**Issue by iclman** [Xray-App/xray-maven-plugin#48]
Hello;

Version of plugin used: 0.6.0  (https://repo1.maven.org/maven2/app/getxray/xray-maven-plugin/0.6.0/) 
Version of Jira used:   v8.20.8
Version of mvn used : 3.6.0

Command maven:
mvn -gs my-global-settings.xml xray:import-results -Dmaven.repo.local=/mytmp/maven-repositories -Dxray.jiraToken=**** -Dxray.jiraBaseUrl=https://myjira.server/ -Dxray.projectKey=ORI2 -Dxray.testPlanKey=ORI2-791 -Dxray.cloud=false -Dxray.reportFormat=junit -Dxray.reportFile=/mytmp/myresults.xml

The test executions tickets are created correctly in Jira
However, the links to the test plan ORI2-791 are not created.

Have you already encountered that kind of issue or did I forget something ?

Thanks

**Comment by iclman** [comment]
Thanks for the update. Is there any plan to perform these fix or evolution on DC/server  in the near future ?

**Comment by bitcoder** [comment]
fixed in version 0.7.0
