### ISSUE TITLE
I don't think the pom.xml snippet is correct on the readme

### ISSUE THREAD

**Issue by terencenmnpan** [Xray-App/xray-maven-plugin#53]
snippet from readme:
```
      <dependency>
            <groupId>app.getxray</groupId>
            <artifactId>xray-maven-plugin</artifactId>
            <version>0.7.0</version>
            <scope>test</scope>
            <configuration>
                <clientId>215FFD69FE46447280000000000</clientId>
                <clientSecret>1c00f8f22f56a8684d7c18cd61470000000</clientSecret>
                <cloud>true</cloud>
                <projectKey>CALC</projectKey>
                <fixVersion>1.0</fixVersion>
                <reportFormat>junit</reportFormat>
                <reportFile>target/junit.xml</reportFile>
            </configuration>
        </dependency>
```

I think it should be like:
```
<plugin>
            <groupId>app.getxray</groupId>
            <artifactId>xray-maven-plugin</artifactId>
            <version>0.7.0</version>
            <configuration>
                <clientId>215FFD69FE46447280000000000</clientId>
                <clientSecret>1c00f8f22f56a8684d7c18cd61470000000</clientSecret>
                <cloud>true</cloud>
                <projectKey>CALC</projectKey>
                <fixVersion>1.0</fixVersion>
                <reportFormat>junit</reportFormat>
                <reportFile>target/junit.xml</reportFile>
            </configuration>
</plugin>
```

**Comment by bitcoder** [comment]
thanks @terencenmnpan , good point.
I think you're right but I'm not 100% sure. 
Can you pls point to some documentation that clarifies that? I found [this](https://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-project-dependencies.html)  but I was unable to find something on the inclusion of plugins on the pom.xml file in that docs.. maybe I missed it.

some other refs:
- https://stackoverflow.com/questions/11881663/what-is-the-difference-in-maven-between-dependency-and-plugin-tags-in-pom-xml
- https://stackoverflow.com/questions/26292073/whats-the-difference-between-maven-plugins-and-dependencies

**Comment by terencenmnpan** [comment]
maven dependency is used when we want to be able to call the library in our code through the classpath. In your case, the xray maven plugin is generally not used to be called in code, but rather used in the build lifecycle with maven to perform a task. We are using your plugin to do the task: send the cucumber report to jira.

In the first stackoverflow article you linked: "But the difference between them is, most of the work in maven is done using plugins; whereas dependency is just a Jar file which will be added to the classpath while executing the tasks."

If you put your plugin in the dependency, nothing will be done in the maven lifecycle. Now if we put your plugin as a plugin, then we can call the goal that will perform our task: mvn xray:import-results

Actually the examples you have are working like this one, the readme file just differs for some reason from the examples:
https://github.com/Xray-App/xray-maven-plugin/blob/main/examples/cloud/pom.xml.sample

**Comment by bitcoder** [comment]
Thanks @terencenmnpan , will fix that

**Comment by bitcoder** [comment]
fixed
