### ISSUE TITLE
Add support for 1.0 Raven

### ISSUE THREAD

**Issue by AddisonSnyder** [Xray-App/xray-maven-plugin#57]
https://github.com/Xray-App/xray-maven-plugin/blob/main/src/main/java/app/getxray/xray/XrayResultsImporter.java#L460

Certain framework specific endpoints (i.e. cucumber) don't work well or don't seem to be supported on 2.0. Can we have an option to override the 2.0 back to the 1.0 API?

**Comment by bitcoder** [comment]
closing for lack of feedback
