### ISSUE TITLE
Multiple Issues observed when uploading the cucumber results

### ISSUE THREAD

**Issue by pothanan** [Xray-App/xray-maven-plugin#61]
In our testing framework, we generate multiple junit test runner classes for cucumber feature files at run time and hence multiple json report files. Then Observed the below issues when trying to upload the multiple cucumber report files using this plugin:

1. Does not accept directory with list of json files ex: target/reports
2. regex does not accept ex: target/reports/*.json
3. socket timeout exception at times because of long response time from Xray Cloud API calls

**Comment by bitcoder** [comment]
Hi @pothanan ,
thanks for reporting but each issue should be reported individually so it can be properly tracked and reproduce.
1) what is the exact configuration you have in your plugin (i.e. on the pom.xml) file? are you using cucumber JSON format?
2) what do you mean exactly with "does not accept"? What is the output? can you run it in verbose mode (see doc for enabling it)?
3) this is a connection issue between your CI/CD and Xray Cloud; in this case I'd recommend reaching out to [Xray support team](https://jira.getxray.app/servicedesk/customer/portal/2) through the support to see if there are any issues on the respective endpoints or not.

**Comment by bitcoder** [comment]
As no further feedback was provided, I will close this issue in the next days
