### ISSUE TITLE
xray:import-features failes including Java DocString

### ISSUE THREAD

**Issue by NielsFeldtmannKALO** [Xray-App/xray-maven-plugin#64]
I'd like the plugin to transfer a Java DocString into the jira ticket

My feature is like 

```
Scenario: A Step with JSON
  Given a JSON
    """
    {
      "any": "thing"
    }
    """
When I call mvn xray:import-features 
Then I want Jira to have the JSON included
```

The created Jira Issue does not contain the content of the DocString

**Comment by orcunbalcilar** [comment]
Hi,
I'm having the same issue. This is probably about xray rest api. Could we find a solution to this problem?

**Comment by bitcoder** [comment]
This is dependent on Xray REST API. For Xray on Jira datacenter the issue on the backlog is: https://jira.getxray.app/browse/XRAY-3365.
You should reach out [Xray support team](https://jira.getxray.app/servicedesk/customer/portal/2); there's nothing we can do in this project.
