### ISSUE TITLE
Import Scenario comment to Jira description field

### ISSUE THREAD

**Issue by NielsFeldtmannKALO** [Xray-App/xray-maven-plugin#65]
Given a test issue in Jira Xray 
And the issue has description = "text in description"
When I export the test to cucumber via the UI
Then I get a comment "text in description" above the tags of the feature

Example of export:

```
#language: de
Funktionalität: Default

	#text in description
	@TEST_UVIX-338
	Szenario: example test
		Angenommen any steps
```

Given a feature in the mentioned format with a comment above the tags of the feature
when I use the   mvn xray:import-features command 
then the comment is written to the description in jira issue

**Comment by bitcoder** [comment]
Are you using Xray on Jira datacenter or Xray on Jira cloud? In Xray cloud this should already be possible.
Supporting this is dependent on what Xray itself supports in the respective REST API endpoint; it's not managed by this plugin.

**Comment by NielsFeldtmannKALO** [comment]
We are running on Data Center.
You are right that this would depend on the Rest API of Xray.
Do you confirm that this issue would we solved with those issues:
https://jira.getxray.app/browse/XRAY-9444
https://jira.getxray.app/browse/XRAY-3365

**Comment by bitcoder** [comment]
I'm closing this issue as it is beyond the scope of this plugin;  please reach our [Xray support team](https://jira.getxray.app/servicedesk/customer/portal/2/user/login?destination=portal%2F2) so they can track your request and point you to the proper issue; I'm not sure if those issues you mentioned cover explicitly what you need but I'll defer that to the support/product team on Xray.
