### ISSUE TITLE
Support for special naming when exporting feature files

### ISSUE THREAD

**Issue by orcunbalcilar** [Xray-App/xray-maven-plugin#67]
When I have exported feature files, they have been named in a format consisting of numeric value and jira issue id. But could we support to name the file as a given one by the user?
Actual -> 1. feature
Desired -> Cucumber.feature

**Comment by bitcoder** [comment]
The naming of the feature files is defined by Xray itself.
The rules for Xray on Jira cloud are detailed [here](https://docs.getxray.app/display/XRAYCLOUD/Generate+Cucumber+Features), and for Xray on Jira datacenter [here](https://docs.getxray.app/display/XRAY/Export+Cucumber+Features).
