### ISSUE TITLE
Split JUnit XML results into multiple files

### ISSUE THREAD

**Issue by rheath-ol** [Xray-App/xray-maven-plugin#76]
The publishing step often fails on large test suites due to file size limitations. Standard Surefire reports are typically split by test class. It would be nice to have the option to do the same with XRay results to avoid file size limitations when publishing reports via the XRay APIs.

**Comment by bitcoder** [comment]
Sorry @rheath-ol , but I think you reported the issue in the wrong project; are you referring to the [xray-junit-extensions](https://github.com/Xray-App/xray-junit-extensions)? If so, please report it there. This plugin doesn't generate JUnit XML reports.
Note: [xray-junit-extensions 0.8.0](https://github.com/Xray-App/xray-junit-extensions/releases/tag/0.8.0) provide the ability to generate Junit XML reports per class btw.
