### ISSUE TITLE
Associate TestExec to Test Plan

### ISSUE THREAD

**Issue by MaherAccor** [Xray-App/xray-maven-plugin#82]
Hello ,
I want to associate the testExec to testPlan after an execution of automation tests .
It works with a reportFormat (Junit , Testng) but not works with a reportFormat (**Cucumber**) .
PS: with the format Junit and testNg the information in not clean , can't import all of steps of scenario Outline.
This my configuration 👍 
<img width="553" alt="Capture d’écran 2024-07-08 à 14 07 12" src="https://github.com/Xray-App/xray-maven-plugin/assets/94442405/af61a258-8035-4453-9d38-bd327dc44653">

**Comment by bitcoder** [comment]
As mentioned on the README, it's not possible to associate the  cucumber resuts to an existing Test Plan, among other, using the "standard" cucumber format. This has to be with the nature of the underlying Cucumber REST API endpoint that doesnt support it.

<img width="827" alt="image" src="https://github.com/Xray-App/xray-maven-plugin/assets/553801/97f05547-176f-41ca-9088-3d5f74dc624c">

You need to use the multipart endpoint instead and provide an auxiliary JSON file to customize the target Test Execution that will be created.
You can see an example of the JSON content on[ this Python script](https://github.com/Xray-App/xray-code-snippets/blob/main/use_cases/import_automation_results/python/import_results_cucumber_multipart_cloud.py) and adapt it aacordingly.

**Comment by MaherAccor** [comment]
Thank you for your response , can you please show me an example of the multipart endPoint because when using an example in the doc for xray i can't associate the testExec with testPlan we have a lot of URL and all of this URL doesn't works.I saw two version api/v1 and api/v2 .
<img width="1015" alt="Capture d’écran 2024-07-08 à 16 10 49" src="https://github.com/Xray-App/xray-maven-plugin/assets/94442405/2fbdbaad-69b9-4661-ba49-47ff7ee31e1a">

**Comment by MaherAccor** [comment]
<img width="1013" alt="Capture d’écran 2024-07-08 à 16 20 12" src="https://github.com/Xray-App/xray-maven-plugin/assets/94442405/020fa871-9cee-4c3f-b048-606e987208e6">

**Comment by bitcoder** [comment]
On the Xray docs you have [another example](https://docs.getxray.app/display/XRAYCLOUD/Import+Execution+Results+-+REST+v2#ImportExecutionResultsRESTv2-CucumberJSONresultsMultipart)

You can use a testExecInfo.json similar to:

json
```
{
    "fields": {
        "project": {
            "key": "CALC"
        },
        "summary": "Brand new Test execution",
        "issuetype": {
            "name": "Test Execution"
        }
    },
    "xrayFields": {
        "testPlanKey": "DEMO-15",
        "environments": ["Chrome"]
    }
}
```

the `environments` field on the previous JSON is optional.


Then on your maven configuration use the `testExecInfoJson` property with the name of the file containing the previous JSON.

**Comment by MaherAccor** [comment]
Thanks 😊 , it works fine now

**Comment by bitcoder** [comment]
Updated the main [README.md](https://github.com/Xray-App/xray-maven-plugin/blob/main/README.md#importing-cucumber-results-and-associating-to-test-plantest-environmentother) file with info on this
