### ISSUE TITLE
Adding support for region based XRay APIs

### ISSUE THREAD

**Issue by sandeepraina-lenze** [Xray-App/xray-maven-plugin#84]
This is a very helpful plugin. Based on current implementation I want to know how can we extend this plugin for region based XRAY APIs.

e.g. default API URL is `https://xray.cloud.getxray.app/`
But if I need to access region based XRAY API like `https://en.xray.cloud.getxray.app/api/v2/`

How can we do it through this plugin.

Please share your insights on this.

**Comment by bitcoder** [comment]
thanks @sandeepraina-lenze , I will need to research it out; will come back whenever I have feedback

**Comment by bitcoder** [comment]
The [official documentation  of Xray Cloud](https://docs.getxray.app/display/XRAYCLOUD/REST+API) now provides that info.
I'll need to revisit the code on this plugin to provide this feature.
Note that you can still use the  https://xray.cloud.getxray.app but it's not the most efficient one.

**Comment by bitcoder** [comment]
@sandeepraina-lenze  can you please try the code on the [cloud_region_endpoints](https://github.com/Xray-App/xray-maven-plugin/tree/cloud_region_endpoints) branch? 
It generates a 0.8.0-beta version. I've update the README file on that branch

**Comment by sandeepraina-lenze** [comment]
Hello @bitcoder and thank for your response on this. This was real quick. I will try with the changes in the branch and will share the feedback with you ASAP.

**Comment by sandeepraina-lenze** [comment]
Quick question, from which location can I pull this build

**Comment by bitcoder** [comment]
I have not generated the build. The code is on the branch that I mentioned. You can checkout the code and build it yourself. If you want a jar, I'll need to send it later

**Comment by bitcoder** [comment]
Here is the package. Install it locally on your local Maven repository and try it out. Unzip it and install it
[xray-maven-plugin-0.8.0-beta.jar.zip](https://github.com/user-attachments/files/16610626/xray-maven-plugin-0.8.0-beta.jar.zip)

**Comment by sandeepraina-lenze** [comment]
Hello @bitcoder

Thank you for the changes, I checked them and they work like charm.

**Comment by sandeepraina-lenze** [comment]
Working as expected
