### ISSUE TITLE
plugin with playwright

### ISSUE THREAD

**Issue by MaherAccor** [Xray-App/xray-maven-plugin#87]
Hello i would like to know if this plugin can be working in playwright with typescript?

**Comment by bitcoder** [comment]
Hi @MaherAccor , in the future you should raise a discussion on the [Discussions](https://github.com/Xray-App/xray-maven-plugin/issues/87#:~:text=Pull%20requests-,Discussions,-Actions) tab of this GitHub project.
Nevertheless, this project is totally independent on the way you implement your automated tests. The scope of this project is to upload test results in a given format (no matter how you generated them) to Xray.
However, this is a maven plugin so it assumes you're using maven as build tool,, which usually is the case for Java projects (not for Typescript projects which use other build tools).

**Comment by MaherAccor** [comment]
sorry i just do that in discussion.
